name: Build All Docker Images

on:
  push:
    branches:
      - main
      - dev   # or any other branch you want
  workflow_dispatch:  # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Web Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/abpdockerweb:latest \
          -f src/AbpDocker.Web/Dockerfile .

    - name: Build IdentityServer Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/abpdockeridentityserver:latest \
          -f src/AbpDocker.IdentityServer/Dockerfile .

    - name: Build HttpApi Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/abpdockerhttpapihost:latest \
          -f src/AbpDocker.HttpApi.Host/Dockerfile .

    - name: Push All Images
      run: |
        docker push ghcr.io/${{ github.repository }}/abpdockerweb:latest
        docker push ghcr.io/${{ github.repository }}/abpdockeridentityserver:latest
        docker push ghcr.io/${{ github.repository }}/abpdockerhttpapihost:latest

